manager/db.go
=> Set branch from config file

manager/manager.go, model/template.go, service/routes.go, service/utils.go
=> Populate catalogId and project link

cmd/root.go, git/git.go, manager/manager.go, service/template.go
Also updates refresh behavior to always update global catalogs.
rancher/rancher#7811
=> Fix refresh interval flag

cmd/root.go, scripts/build
=> Add version flag

service/template.go
=> Support minimumRancherVersion_lte for older versions of CLI

integration/core/test_api.py, manager/db.go
=> Preserve category case

integration/core/test_api.py, model/catalog.go, model/template.go, model/version.go, service/catalog.go, service/routes.go, service/template.go
=> Return 404 when catalog/template/version not found

manager/db.go, manager/manager.go
rancher/rancher#8029
rancher/rancher#8030
=> Don't create catalog until templates are populated

manager/manager.go
=> Gracefully handle bad catalogs

helm/helm.go, helm/helm_filter.go, manager/manager.go, manager/traverse.go
=> filter non-valid helm files

integration/core/test_api.py, service/catalog.go, service/template.go, service/utils.go
https://github.com/rancher/rancher/issues/8701
Rancher server version used for local testing is: `rancher/server:v1.6.0-rc1`
Able to hit via:
`http://localhost:8080/v1-catalog/templates/apache:apache?image&projectId=1a7`
Where `apache:apache` is the template and `1a7` is the environment id
=> Create template based on environment ID

integration/core/test_api.py, service/catalog.go, service/routes.go
=> Edit existing catalog

integration/core/test_api.py, service/catalog.go, service/utils.go
Addresses https://github.com/rancher/rancher/issues/8776 and https://github.com/rancher/rancher/issues/8766
=> Duplicate catalog name & Edit catalog

manager/traverse.go
Adds support for file names template.yml and icon.extension https://github.com/rancher/rancher/issues/8319
=> Config file

integration/core/test_api.py, manager/traverse.go, parse/compose.go, service/utils.go
Add support for template-version.yml, removes catalog field for template-version.yml, and only includes the old catalog fields. https://github.com/rancher/rancher/issues/8319
=> Add support for template-version.yml and remove catalog field

git/git.go, integration/core/test_api.py, manager/local.go
Addresses this issue: https://github.com/rancher/rancher/issues/9057
=> optimize catalog fetch

tracking/tracking.go
Adjust environment variables to match the injected environment variables in https://github.com/rancher/cattle/pull/2801
=> Fix Rancher API credentials

manager/local.go
This is useful for users to check to make sure their catalogs have updated. As well as for QA to check for changes.
Addresses: https://github.com/rancher/rancher/issues/9228
=> logging for catalog update

git/git.go
https://github.com/rancher/rancher/issues/9378
=> fix for airgap network catalog service panic issue

git/git.go
https://github.com/rancher/rancher/issues/9378
=> fix for airgap network catalog issue

integration/core/test_api.py, model/version.go, service/utils.go
https://github.com/rancher/rancher/issues/8998
=> Implement default version for template and default upgrade version for template version
